name: example
description: Showcase Example CLI for purecast
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  purecast:
    path: ../
  logging: ^1.0.1
  args: ^2.3.0
